name: Deploy aws-blog to EC2

# Trigger only on push to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up SSH to EC2
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H YOUR_EC2_PUBLIC_IP >> ~/.ssh/known_hosts

      # 3️⃣ Deploy code
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@YOUR_EC2_PUBLIC_IP "
            cd /home/ec2-user/AWSblog

            # Pull latest code
            git pull origin main

            # Virtual environment setup
            if [ -d 'venv' ]; then
              source venv/bin/activate
            else
              python3 -m venv venv
              source venv/bin/activate
              pip install --upgrade pip
              pip install -r requirements.txt
            fi

            # Restart Flask app
            if systemctl list-units --full -all | grep -Fq 'awsblog.service'; then
              sudo systemctl restart awsblog.service
            else
              pkill -f 'python3 app.py' || true
              nohup python3 app.py &
            fi
          "
