name: Deploy to EC2

on:
  push:
    branches:
      - main   # change if you use another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup SSH
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.YOUR_EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ec2-user/cicd
            # Remove old repo if exists
            rm -rf AWSblog
            # Clone fresh repo
            git clone https://github.com/theritikbarnwal/AWSblog.git
            cd AWSblog   # ✅ Go inside cloned repo

            if [ -d 'venv' ]; then
              source venv/bin/activate
              pip install -r requirements.txt
            else
              python3 -m venv venv
              source venv/bin/activate
              pip install --upgrade pip
              pip install -r requirements.txt
            fi

            if systemctl list-units --full -all | grep -Fq 'awsblog.service'; then
              sudo systemctl restart awsblog.service
            else
              pkill -f 'python3 app.py' || true
              nohup python3 app.py > flask.log 2>&1 &
            fi
          EOF
